### ISSUE TITLE
Can the code of InterHand be made public?

### ISSUE THREAD

**Issue by zqq-judy** [yihui-he/epipolar-transformers#19] opened 2021-04-02 10:50 UTC
Hello!
Can you share the relevant code of InterHand? For example, yaml file  and dataloader.
Thank you!
Best wishes!

**Comment by yihui-he** [comment] 2021-08-24 09:17
@endoplasmic1357 can we release this part?

**Comment by yihui-he** [comment] 2021-08-24 09:18
Duplicate of #14

**Closed by yihui-he** 2021-08-24 09:18 UTC
