### ISSUE TITLE
dataset dir

### ISSUE THREAD

**Issue by sherrywan** [yihui-he/epipolar-transformers#20] opened 2021-04-27 07:36 UTC
Hello,
I really liked your work and would like to test the network !

I have one more question, where should be changed after using H36M-Toolbox. I cannot find the zip file.

Thank you very much in advance for your answers !

Best regards.

**Comment by yihui-he** [comment] 2021-05-19 18:59
Duplicate of #11

**Closed by yihui-he** 2021-05-19 18:59 UTC
