### ISSUE TITLE
Question about the number of views and MPJPE

### ISSUE THREAD

**Issue by asw91666** [yihui-he/epipolar-transformers#23] opened 2021-07-13 04:47 UTC
Hi.
I think the MPJPE will be improved if you use all of views of h36m(4 views). but you use just 1 other views(keypoint_h36m_resnet152_384_pretrained_8gpu.yaml).

Can you explain Could you explain why you didn't use 4 views?

**Comment by yihui-he** [comment] 2021-08-24 09:15
it's not implemented yet. 
Duplicate of #10

**Closed by yihui-he** 2021-08-24 09:15 UTC
